<!DOCTYPE html> 
<html> 

<head> 
	<title> 
		Why is it possible to try-catch 
		an async-await call ? 
	</title> 
</head> 

<body> 
	<span>Click the button</span> 

	<button onclick="fetch()"> 
		Click here 
	</button> 
	
	<script> 
		async function fetch(){
    try{
        const response = await fetch('https://jsonplaceholder.typicode.com/posts/1');
        // console.log(response);
        const data = await response.json();
        console.log(data);
    }
    catch(error){
        console.log(error)
    }
}
	</script> 
</body> 

</html>
